language: node_js
node_js:
- '0.11'
branches:
  only:
  - master
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: kendrick.coleman@emc.com
  password:
    secure: kI9YyrfIGxqj8OEJfd8XADnn8jwW9cHO6KX9X64hqZjnb1xjqtt6x9R6WqMKwypEpsiifSEGYVxOAcDEyVqWHfiRynGZzxORXTsyadVTcX7eBltRU1kdBpM3tT+PQLTO3uw1jFBpEAaOagCK0umb3EQYOxkCo2KTriZWfB10d2i+lcFYB/RhMFCdFLsqdDutHn3klP1YbBgrLlp/mpCvZdt266jScUOCHWOeJ2m3UC6YULbZm1M6l/L+rX+YxY/7gzFltOd1yPi7YyJvyhuh0FX2FwyM2JhiQwT1hTojm35qDYNpwsRm823qloJ3TVvg4Cj+o+Gj1TKVS65qwSa6NtdjYwbSUK1nd0VQ8emXXaM4fra3gWiqrMYhIBrZGCl/eGiudVfEyYsNAl4s9fG1DUD2+gf/84laXidPEbUb1JRjsuIMgZtmdsqzfv/GKvPO15O49721061b7bRQzdYp75soTW/J7Ji0YTsD6k40ZRmt83oTFSqgVCq6FbmAoMlfENYp8OOUoQia2/AVxW6mX4wuUlF5MontVIffPn70hZii0822Kj889wblC2m252UNf3j6XDz8QtDzSLpTQ8ev1gGdatQWx4LMqpLAFT81Gek2PnnqFRJPjz5RWlpKyWOn5aUUe2GGOzlSlI8P3WyobWnAe2Xh5zuK4+RfkOzE6GY=
  organization: emccode
  space: production
  on:
    repo: kacole2/rexray-config-generator

